### ISSUE TITLE
usename and password to login

### ISSUE THREAD

**Issue by miladev95** [postfixadmin/docker#52]
My Docker compose
```
db:
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: postfixadmin
       MYSQL_USER: postfixadmin
       MYSQL_PASSWORD: 123

  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 8000:80
    restart: always
    environment:
       POSTFIXADMIN_DB_TYPE: mysqli
       POSTFIXADMIN_DB_HOST: db
       POSTFIXADMIN_DB_USER: postfixadmin
       POSTFIXADMIN_DB_NAME: postfixadmin
       POSTFIXADMIN_DB_PASSWORD: 123
       POSTFIXADMIN_SMTP_SERVER: postfix
       POSTFIXADMIN_SMTP_PORT: 25
       POSTFIXADMIN_SETUP_PASSWORD: 123
       POSTFIXADMIN_ENCRYPT: md5crypt 
```

i tried so many username and password but  `http://localhost:8000/login.php ` says  `Your email address or password is not correct.`

how can i find default username and password?
