### ISSUE TITLE
`/dev/tcp/db/3306: Connection refused` using MySQL

### ISSUE THREAD

**Issue by waffle87** [postfixadmin/docker#77]
When using the example Compose file and changing the password parameters, the container crashes with the following error (and `config.local.php`)
```
postfixadmin-1  | Postfixadmin not found in /var/www/html - copying now...
postfixadmin-1  | Complete! Postfixadmin has been successfully copied to /var/www/html
postfixadmin-1  | bash: connect: Connection refused
postfixadmin-1  | bash: line 1: /dev/tcp/db/3306: Connection refused
postfixadmin-1  | bash: connect: Connection refused
postfixadmin-1  | bash: line 1: /dev/tcp/db/3306: Connection refused
postfixadmin-1  | bash: connect: Connection refused
postfixadmin-1  | bash: line 1: /dev/tcp/db/3306: Connection refused
postfixadmin-1  | bash: connect: Connection refused
postfixadmin-1  | bash: line 1: /dev/tcp/db/3306: Connection refused
postfixadmin-1  | bash: connect: Connection refused
postfixadmin-1  | bash: line 1: /dev/tcp/db/3306: Connection refused
postfixadmin-1  | Write config to /var/www/html/config.local.php
postfixadmin-1  | <?php
postfixadmin-1  | 		$CONF['database_type'] = 'mysqli';
postfixadmin-1  | 		$CONF['database_host'] = 'db';
postfixadmin-1  | 		$CONF['database_port'] = '3306';
postfixadmin-1  | 		$CONF['database_user'] = 'postfixadmin';
postfixadmin-1  | 		$CONF['database_password'] = 'foobarbaz';
postfixadmin-1  | 		$CONF['database_name'] = 'postfixadmin';
postfixadmin-1  | 		$CONF['setup_password'] = 'changeme';
postfixadmin-1  | 		$CONF['smtp_server'] = 'postfix';
postfixadmin-1  | 		$CONF['smtp_port'] = '25';
postfixadmin-1  | 		$CONF['encrypt'] = 'md5crypt';
postfixadmin-1  | 		$CONF['configured'] = true;
postfixadmin-1  | 		$CONF['dkim'] = 'NO';
postfixadmin-1  | 		$CONF['dkim_all_admins'] = 'NO';
postfixadmin-1  | 		?>
```
I tried various different things like explicitly setting the port in the MySQL container configuration, setting the host to `db;port=3306` in `config.local.php`, etc. with no luck and all resulted in the same error. For posterity, here is the `compose.yaml` file used to produce this.
```yaml
services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: foobarbaz
       MYSQL_DATABASE: postfixadmin
       MYSQL_USER: postfixadmin
       MYSQL_PASSWORD: foobarbaz

   postfixadmin:
     depends_on:
       - db
     image: postfixadmin:apache
     ports:
       - "8000:80"
     restart: always
     environment:
       POSTFIXADMIN_DB_TYPE: mysqli
       POSTFIXADMIN_DB_HOST: db
       POSTFIXADMIN_DB_USER: postfixadmin
       POSTFIXADMIN_DB_NAME: postfixadmin
       POSTFIXADMIN_DB_PASSWORD: foobarbaz
       POSTFIXADMIN_SMTP_SERVER: postfix
       POSTFIXADMIN_SMTP_PORT: 25
       POSTFIXADMIN_ENCRYPT: md5crypt
```

**Comment by DavidGoodwin** [comment]
`docker compose run -ti postfixadmin /bin/bash`

...
apt-get install telnet
...

```
root@636b1214d517:/var/www/html# telnet db 3306
Trying 172.19.0.2...
Connected to db.
Escape character is '^]'.
CHost '172.19.0.3' is not allowed to connect to this MySQL serverConnection closed by foreign host.
```

**Comment by DavidGoodwin** [comment]
try this : 

```
services:
   db:
     image: mysql:5.7
     restart: always
     expose:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: foobarbaz
       MYSQL_DATABASE: postfixadmin
       MYSQL_USER: postfixadmin
       MYSQL_PASSWORD: foobarbaz
     ulimits:
       nofile:
         soft: "262144"
         hard: "262144"

   postfixadmin:
     depends_on:
       - db
     image: postfixadmin:apache
     ports:
       - "8000:80"
     restart: always
     environment:
       POSTFIXADMIN_DB_TYPE: mysqli
       POSTFIXADMIN_DB_HOST: db
       POSTFIXADMIN_DB_USER: postfixadmin
       POSTFIXADMIN_DB_NAME: postfixadmin
       POSTFIXADMIN_DB_PASSWORD: foobarbaz
       POSTFIXADMIN_SMTP_SERVER: postfix
       POSTFIXADMIN_SMTP_PORT: 25
       POSTFIXADMIN_ENCRYPT: md5crypt
```
